/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppSeguradorasRouteImport } from './routes/_app.seguradoras'
import { Route as AppPlanosRouteImport } from './routes/_app.planos'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppAutomacoesRouteImport } from './routes/_app.automacoes'
import { Route as AppClientesIdRouteImport } from './routes/_app.clientes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppSeguradorasRoute = AppSeguradorasRouteImport.update({
  id: '/seguradoras',
  path: '/seguradoras',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/historico': typeof AppHistoricoRoute
  '/logs': typeof AppLogsRoute
  '/planos': typeof AppPlanosRoute
  '/seguradoras': typeof AppSeguradorasRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/clientes/$id': typeof AppClientesIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/historico': typeof AppHistoricoRoute
  '/logs': typeof AppLogsRoute
  '/planos': typeof AppPlanosRoute
  '/seguradoras': typeof AppSeguradorasRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/': typeof AppIndexRoute
  '/clientes/$id': typeof AppClientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/automacoes': typeof AppAutomacoesRoute
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/planos': typeof AppPlanosRoute
  '/_app/seguradoras': typeof AppSeguradorasRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/automacoes'
    | '/clientes'
    | '/historico'
    | '/logs'
    | '/planos'
    | '/seguradoras'
    | '/whatsapp'
    | '/clientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/automacoes'
    | '/clientes'
    | '/historico'
    | '/logs'
    | '/planos'
    | '/seguradoras'
    | '/whatsapp'
    | '/'
    | '/clientes/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/automacoes'
    | '/_app/clientes'
    | '/_app/historico'
    | '/_app/logs'
    | '/_app/planos'
    | '/_app/seguradoras'
    | '/_app/whatsapp'
    | '/_app/'
    | '/_app/clientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seguradoras': {
      id: '/_app/seguradoras'
      path: '/seguradoras'
      fullPath: '/seguradoras'
      preLoaderRoute: typeof AppSeguradorasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos': {
      id: '/_app/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automacoes': {
      id: '/_app/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesIdRoute: typeof AppClientesIdRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesIdRoute: AppClientesIdRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteChildren {
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppLogsRoute: typeof AppLogsRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppSeguradorasRoute: typeof AppSeguradorasRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppHistoricoRoute: AppHistoricoRoute,
  AppLogsRoute: AppLogsRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppSeguradorasRoute: AppSeguradorasRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
